apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-db-pvc
  namespace: e-commerce
spec:
  storageClassName: nfs-client # Use the working NFS provisioner
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
