apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: e-commerce
spec:
  # Internal ClusterIP is sufficient as only the Frontend calls it
  type: ClusterIP 
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 5001       # Service port
      targetPort: 5001 # Container port
