apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: e-commerce
spec:
  type: NodePort # Exposed for external access via the Worker Node IP
  selector:
    app: e-commerce-frontend
  ports:
    - protocol: TCP
      port: 80       # Service port
      targetPort: 80 # Container port
