apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-db-pvc
  namespace: e-commerce
spec:
  accessModes:
    - ReadWriteOnce # Only one node can mount this volume at a time
  resources:
    requests:
      storage: 1Gi
