apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: e-commerce
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 80 # Service port (internal cluster communication)
      targetPort: 5000 # Container port
